[package]
name = "during"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.33"}
chrono-tz = "0.8.5"
clap = { version = "4.4.18", features = ["derive"] }
regex = "1.10.3"
